### ISSUE TITLE
Re-running worker-runner after it has fetched credentials from AWS provisioner userdata fails

### ISSUE THREAD

**Issue by milescrabill** [taskcluster/taskcluster-worker-runner#26]
After worker-runner has gotten credentials for its worker from AWS provisioner (or used the credentials from userdata at all) they are invalidated. If worker-runner is run again, it will attempt to re-use those credentials and will fail, as they will have been deleted.

My expectation is that worker-runner is the interface we use to interact with / run the worker, so it should be able to be cleanly restarted. This might mean that in addition to provisioning credentials for the worker after using the temporary userdata credentials, worker-runner should provision its own credentials, or that it should use the worker's credentials after that point.

**Comment by djmitche** [comment]
Partly, this is totally intentional: the worker instance runs arbitrary code, and we do not want that code to be able to fetch valid worker credentials.  So once the worker itself has gotten credentials, no further credentials are allowed.

But, I think the functionality that you're looking for is that worker-runner would be able to start a worker process multiple times on that worker instance, such as over restarts.  That is supported, thanks to #16
