### ISSUE TITLE
workerConfig docs incorrect

### ISSUE THREAD

**Issue by aerickson** [taskcluster/taskcluster-worker-runner#94]
The docs about workerConfig don't seem correct, my block of configuration for g-w (the right side in the diff below) generates an identical config to the current taskcluster-worker-runner-less setup for bitbar but differs from what https://github.com/taskcluster/taskcluster-worker-runner#provider-configuration recommends. 

- https://github.com/bclary/mozilla-bitbar-docker/pull/40/commits/363dbd6b732e7253a11d8fe79d757cfce0943420 shows the recommended structure on left (that didn't generate an identical config) and the config that does generate an identical config on the right.
  - The config on the left generated a g-w config that g-w did not like. The config options were under genericWorker.config vs being at the base.

**Comment by djmitche** [comment]
Those docs are for the workerConfig field in a worker pool, so this is at least working as expected.  But, I can see the confusion!  I suppose the options are to document it more clearly, or to implement support for the nested form here as well.

I'd prefer to document it more clearly.  The reasoning is, the more nested form allows `files`, and allows configuration of things other than `genericWorker` (for example, we will probably add `workerRunner` at some point).  Neither of those are appropriate *within* the runner config, though: if you want to create a file on disk, just do so (it's the same disk as that containing the runner config); and if you want to configure worker runner, do that at the top level of the runner config file, rather than nested in a sub-property of that same file.

Does that sound reasonable?

**Comment by aerickson** [comment]
Aaaah, OK. Yeah, clarifying the docs sounds good to me. Thanks!
